# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49338d90f8cf38487171e73eb865f4fc22ef9f2b6e7b3f96d6fdcafdd4b5a45bda2208f78e703c639f21f9a14fef185cd0abfa3d67b0c5192b4049805e577f6b

test:
  secret_key_base: 5d4e8a528ce200efed9a55918e467ae01e467a6a76a40150022f82daea0067b8a56ad6cd60576d219e943bc05874eb6a4bbb74916a54683ef6e7f4b504057821

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
